name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: |
          echo "Pinging Render backend..."
          curl -fsS https://currency-converter-e4i2.onrender.com/health || echo "App may be asleep or down"
          echo "Ping completed at $(date)"
